export const users = [
  {
    db_column_name: 'p_email',
    is_dimension: true,
    is_permitted: true,
    has_dict: false,
    is_common: false,
    cname: 'Email',
    is_user_tag: false,
    is_measure: false,
    pinyin: 'Email',
    name: 'Email',
    data_type: 'string',
    id: 472,
    has_db_column_name: true,
    not_select_group: false,
  },
  {
    db_column_name: 'p__mp_wx6228eb2adfba3ab4_qr_scene_str',
    is_dimension: true,
    is_permitted: true,
    has_dict: false,
    is_common: false,
    cname: 'Sensors Bullet 二维码扫码场景描述',
    is_user_tag: false,
    is_measure: false,
    pinyin: 'Sensors Bullet  er wei ma sao ma chang jing miao shu',
    name: '$mp_wx6228eb2adfba3ab4_qr_scene_str',
    data_type: 'string',
    id: 510,
    has_db_column_name: true,
    not_select_group: false,
  },
  {
    db_column_name: 'p__mp_wx6228eb2adfba3ab4_openid',
    is_dimension: true,
    is_permitted: true,
    has_dict: false,
    is_common: false,
    cname: 'Sensors Bullet 用户 openid',
    is_user_tag: false,
    is_measure: false,
    pinyin: 'Sensors Bullet  yong hu  openid',
    name: '$mp_wx6228eb2adfba3ab4_openid',
    data_type: 'string',
    id: 492,
    has_db_column_name: true,
    not_select_group: false,
  },
  {
    db_column_name: 'p__mp_wx6228eb2adfba3ab4_qr_scene',
    is_dimension: true,
    is_permitted: true,
    has_dict: false,
    is_common: false,
    cname: '用户二维码扫码场景',
    is_user_tag: false,
    is_measure: true,
    pinyin: 'Sensors Bullet  yong hu er wei ma sao ma chang jing',
    name: '$mp_wx6228eb2adfba3ab4_qr_scene',
    data_type: 'number',
    id: 509,
    has_db_column_name: true,
    not_select_group: false,
  },
  {
    db_column_name: 'p__external_5',
    is_dimension: true,
    is_permitted: true,
    has_dict: true,
    is_common: false,
    cname: 'Sensors Bullet 用户关注来源',
    is_user_tag: false,
    is_measure: false,
    pinyin: 'Sensors Bullet  yong hu guan zhu lai yuan',
    name: '$mp_wx6228eb2adfba3ab4_subscribe_scene',
    data_type: 'string',
    id: 505,
    has_db_column_name: true,
    not_select_group: false,
  },
  {
    db_column_name: 'p__mp_wx6228eb2adfba3ab4_remark',
    is_dimension: true,
    is_permitted: true,
    has_dict: false,
    is_common: false,
    cname: 'Sensors Bullet 用户备注',
    is_user_tag: false,
    is_measure: false,
    pinyin: 'Sensors Bullet  yong hu bei zhu',
    name: '$mp_wx6228eb2adfba3ab4_remark',
    data_type: 'string',
    id: 493,
    has_db_column_name: true,
    not_select_group: false,
  },
  {
    db_column_name: 'p__mp_wx6228eb2adfba3ab4_subscribe',
    is_dimension: true,
    is_permitted: true,
    has_dict: false,
    is_common: false,
    cname: 'Sensors Bullet 用户是否关注公众号',
    is_user_tag: false,
    is_measure: false,
    pinyin: 'Sensors Bullet  yong hu shi fou guan zhu gong zhong hao',
    name: '$mp_wx6228eb2adfba3ab4_subscribe',
    data_type: 'bool',
    id: 496,
    has_db_column_name: true,
    not_select_group: false,
  },
  {
    db_column_name: 'p__mp_wx6228eb2adfba3ab4_is_in_blacklist',
    is_dimension: true,
    is_permitted: true,
    has_dict: false,
    is_common: false,
    cname: 'Sensors Bullet 用户是否在黑名单中',
    is_user_tag: false,
    is_measure: false,
    pinyin: 'Sensors Bullet  yong hu shi fou zai hei ming dan zhong',
    name: '$mp_wx6228eb2adfba3ab4_is_in_blacklist',
    data_type: 'bool',
    id: 495,
    has_db_column_name: true,
    not_select_group: false,
  },
  {
    db_column_name: 'p__mp_wx6228eb2adfba3ab4_latest_interactive_time',
    is_dimension: true,
    is_permitted: true,
    has_dict: false,
    is_common: false,
    cname: 'Sensors Bullet 用户最近互动时间',
    is_user_tag: false,
    is_measure: false,
    pinyin: 'Sensors Bullet  yong hu zui jin hu dong shi jian',
    name: '$mp_wx6228eb2adfba3ab4_latest_interactive_time',
    data_type: 'datetime',
    id: 507,
    has_db_column_name: true,
    not_select_group: false,
  },
  {
    db_column_name: 'p__mp_wx6228eb2adfba3ab4_subscribe_time',
    is_dimension: true,
    is_permitted: true,
    has_dict: false,
    is_common: false,
    cname: 'Sensors Bullet 用户最近关注时间',
    is_user_tag: false,
    is_measure: false,
    pinyin: 'Sensors Bullet  yong hu zui jin guan zhu shi jian',
    name: '$mp_wx6228eb2adfba3ab4_subscribe_time',
    data_type: 'datetime',
    id: 506,
    has_db_column_name: true,
    not_select_group: false,
  },
  {
    db_column_name: 'p__mp_wx6228eb2adfba3ab4_tagid_list',
    is_dimension: false,
    is_permitted: true,
    has_dict: false,
    is_common: false,
    cname: 'Sensors Bullet 用户标签列表',
    is_user_tag: false,
    is_measure: false,
    pinyin: 'Sensors Bullet  yong hu biao qian lie biao',
    name: '$mp_wx6228eb2adfba3ab4_tagid_list',
    data_type: 'list',
    id: 500,
    has_db_column_name: true,
    not_select_group: false,
  },
  {
    db_column_name: 'p_acceptable_maximum_loss',
    is_dimension: true,
    is_permitted: true,
    has_dict: false,
    is_common: false,
    cname: 'acceptable_maximum_loss',
    is_user_tag: false,
    is_measure: true,
    pinyin: 'acceptable_maximum_loss',
    name: 'acceptable_maximum_loss',
    data_type: 'number',
    id: 422,
    has_db_column_name: true,
    not_select_group: false,
  },
];

export const events = [
  {
    id: 81,
    bucket_id: 0,
    virtual: false,
    visible: true,
    name: '$pageView',
    cname: '$pageView',
  },
  {
    id: 155,
    bucket_id: 8,
    virtual: false,
    visible: true,
    name: 'addToShoppingCart',
    cname: 'addToShoppingCart',
  },
  {
    id: 95,
    bucket_id: 12,
    virtual: false,
    visible: true,
    name: '$AppClick',
    cname: 'App 元素点击',
  },
  {
    id: 116,
    bucket_id: 10,
    virtual: false,
    visible: true,
    name: '$AppStart',
    cname: 'App 启动',
  },
  {
    id: 61,
    bucket_id: 1,
    virtual: false,
    visible: true,
    name: '$AppPushClick',
    cname: 'App 推送点击',
  },
  {
    id: 117,
    bucket_id: 11,
    virtual: false,
    visible: true,
    name: '$AppViewScreen',
    cname: 'App 浏览页面',
  },
  {
    id: 150,
    bucket_id: 3,
    virtual: false,
    visible: true,
    name: 'AppInstall',
    cname: 'App 激活',
  },
  {
    id: 80,
    bucket_id: 10,
    virtual: false,
    visible: true,
    name: '$AppEnd',
    cname: 'App 退出',
  },
  {
    id: 158,
    bucket_id: 1,
    virtual: false,
    visible: true,
    name: 'applyReturn',
    cname: 'applyReturn',
  },
  {
    id: 92,
    bucket_id: 9,
    virtual: false,
    visible: true,
    name: 'bannerClick',
    cname: 'bannerClick',
  },
  {
    id: 110,
    bucket_id: 5,
    virtual: false,
    visible: true,
    name: 'buyBefore',
    cname: 'buyBefore',
  },
  {
    id: 107,
    bucket_id: 3,
    virtual: false,
    visible: true,
    name: 'buyNow',
    cname: 'buyNow',
  },
  {
    id: 78,
    bucket_id: 8,
    virtual: false,
    visible: true,
    name: 'cancelOrder',
    cname: 'cancelOrder',
  },
  {
    id: 103,
    bucket_id: 9,
    virtual: false,
    visible: true,
    name: 'cancelOrderDetail',
    cname: 'cancelOrderDetail',
  },
  {
    id: 118,
    bucket_id: 1,
    virtual: false,
    visible: true,
    name: 'case107_event01',
    cname: 'case107_event01',
  },
  {
    id: 119,
    bucket_id: 2,
    virtual: false,
    visible: true,
    name: 'case107_event02',
    cname: 'case107_event02',
  },
  {
    id: 120,
    bucket_id: 3,
    virtual: false,
    visible: true,
    name: 'case108_event01',
    cname: 'case108_event01',
  },
  {
    id: 121,
    bucket_id: 4,
    virtual: false,
    visible: true,
    name: 'case108_event02',
    cname: 'case108_event02',
  },
];
export const products = [
  {
    name: 'video',
    cname: 'video',
  },
  {
    name: 'article',
    cname: 'article',
  },
  {
    name: 'fund',
    cname: 'fund',
  },
  {
    name: 'spe_banner',
    cname: 'spe_banner',
  },
  {
    name: 'goods',
    cname: 'goods',
  },
  {
    name: 'test_spe_banner',
    cname: 'test_spe_banner',
  },
];

export const whites = [
  {
    db_column_name: 'p_email',
    is_dimension: true,
    is_permitted: true,
    has_dict: false,
    is_common: false,
    cname: 'Email',
    is_user_tag: false,
    is_measure: false,
    pinyin: 'Email',
    name: 'Email',
    data_type: 'string',
    id: 472,
    has_db_column_name: true,
    not_select_group: false,
  },
  {
    db_column_name: 'p__mp_wx6228eb2adfba3ab4_qr_scene_str',
    is_dimension: true,
    is_permitted: true,
    has_dict: false,
    is_common: false,
    cname: 'Sensors Bullet 二维码扫码场景描述',
    is_user_tag: false,
    is_measure: false,
    pinyin: 'Sensors Bullet  er wei ma sao ma chang jing miao shu',
    name: '$mp_wx6228eb2adfba3ab4_qr_scene_str',
    data_type: 'string',
    id: 510,
    has_db_column_name: true,
    not_select_group: false,
  },
  {
    db_column_name: 'p__mp_wx6228eb2adfba3ab4_openid',
    is_dimension: true,
    is_permitted: true,
    has_dict: false,
    is_common: false,
    cname: 'Sensors Bullet 用户 openid',
    is_user_tag: false,
    is_measure: false,
    pinyin: 'Sensors Bullet  yong hu  openid',
    name: '$mp_wx6228eb2adfba3ab4_openid',
    data_type: 'string',
    id: 492,
    has_db_column_name: true,
    not_select_group: false,
  },
  {
    db_column_name: 'p__mp_wx6228eb2adfba3ab4_qr_scene',
    is_dimension: true,
    is_permitted: true,
    has_dict: false,
    is_common: false,
    cname: '用户二维码扫码场景',
    is_user_tag: false,
    is_measure: true,
    pinyin: 'Sensors Bullet  yong hu er wei ma sao ma chang jing',
    name: '$mp_wx6228eb2adfba3ab4_qr_scene',
    data_type: 'number',
    id: 509,
    has_db_column_name: true,
    not_select_group: false,
  },
  {
    db_column_name: 'p__external_5',
    is_dimension: true,
    is_permitted: true,
    has_dict: true,
    is_common: false,
    cname: 'Sensors Bullet 用户关注来源',
    is_user_tag: false,
    is_measure: false,
    pinyin: 'Sensors Bullet  yong hu guan zhu lai yuan',
    name: '$mp_wx6228eb2adfba3ab4_subscribe_scene',
    data_type: 'string',
    id: 505,
    has_db_column_name: true,
    not_select_group: false,
  },
  {
    db_column_name: 'p__mp_wx6228eb2adfba3ab4_remark',
    is_dimension: true,
    is_permitted: true,
    has_dict: false,
    is_common: false,
    cname: 'Sensors Bullet 用户备注',
    is_user_tag: false,
    is_measure: false,
    pinyin: 'Sensors Bullet  yong hu bei zhu',
    name: '$mp_wx6228eb2adfba3ab4_remark',
    data_type: 'string',
    id: 493,
    has_db_column_name: true,
    not_select_group: false,
  },
  {
    db_column_name: 'p__mp_wx6228eb2adfba3ab4_subscribe',
    is_dimension: true,
    is_permitted: true,
    has_dict: false,
    is_common: false,
    cname: 'Sensors Bullet 用户是否关注公众号',
    is_user_tag: false,
    is_measure: false,
    pinyin: 'Sensors Bullet  yong hu shi fou guan zhu gong zhong hao',
    name: '$mp_wx6228eb2adfba3ab4_subscribe',
    data_type: 'bool',
    id: 496,
    has_db_column_name: true,
    not_select_group: false,
  },
  {
    db_column_name: 'p__mp_wx6228eb2adfba3ab4_is_in_blacklist',
    is_dimension: true,
    is_permitted: true,
    has_dict: false,
    is_common: false,
    cname: 'Sensors Bullet 用户是否在黑名单中',
    is_user_tag: false,
    is_measure: false,
    pinyin: 'Sensors Bullet  yong hu shi fou zai hei ming dan zhong',
    name: '$mp_wx6228eb2adfba3ab4_is_in_blacklist',
    data_type: 'bool',
    id: 495,
    has_db_column_name: true,
    not_select_group: false,
  },
  {
    db_column_name: 'p__mp_wx6228eb2adfba3ab4_latest_interactive_time',
    is_dimension: true,
    is_permitted: true,
    has_dict: false,
    is_common: false,
    cname: 'Sensors Bullet 用户最近互动时间',
    is_user_tag: false,
    is_measure: false,
    pinyin: 'Sensors Bullet  yong hu zui jin hu dong shi jian',
    name: '$mp_wx6228eb2adfba3ab4_latest_interactive_time',
    data_type: 'datetime',
    id: 507,
    has_db_column_name: true,
    not_select_group: false,
  },
  {
    db_column_name: 'p__mp_wx6228eb2adfba3ab4_subscribe_time',
    is_dimension: true,
    is_permitted: true,
    has_dict: false,
    is_common: false,
    cname: 'Sensors Bullet 用户最近关注时间',
    is_user_tag: false,
    is_measure: false,
    pinyin: 'Sensors Bullet  yong hu zui jin guan zhu shi jian',
    name: '$mp_wx6228eb2adfba3ab4_subscribe_time',
    data_type: 'datetime',
    id: 506,
    has_db_column_name: true,
    not_select_group: false,
  },
  {
    db_column_name: 'p__mp_wx6228eb2adfba3ab4_tagid_list',
    is_dimension: false,
    is_permitted: true,
    has_dict: false,
    is_common: false,
    cname: 'Sensors Bullet 用户标签列表',
    is_user_tag: false,
    is_measure: false,
    pinyin: 'Sensors Bullet  yong hu biao qian lie biao',
    name: '$mp_wx6228eb2adfba3ab4_tagid_list',
    data_type: 'list',
    id: 500,
    has_db_column_name: true,
    not_select_group: false,
  },
  {
    db_column_name: 'p_acceptable_maximum_loss',
    is_dimension: true,
    is_permitted: true,
    has_dict: false,
    is_common: false,
    cname: 'acceptable_maximum_loss',
    is_user_tag: false,
    is_measure: true,
    pinyin: 'acceptable_maximum_loss',
    name: 'acceptable_maximum_loss',
    data_type: 'number',
    id: 422,
    has_db_column_name: true,
    not_select_group: false,
  },
];

export const getEventProps = () =>
  new Promise((resolve) => {
    setTimeout(() => {
      resolve([
        {
          db_column_name: 'distinct_id',
          is_dimension: true,
          is_permitted: true,
          has_dict: false,
          cname: 'Distinct ID',
          is_measure: false,
          pinyin: 'Distinct ID',
          event_id: 95,
          name: '$distinct_id',
          data_type: 'string',
          event_name: '$AppClick',
          id: 2001003,
          has_db_column_name: true,
          not_select_group: false,
        },
        {
          db_column_name: 'p__ip',
          is_dimension: true,
          is_permitted: true,
          has_dict: false,
          is_common: false,
          cname: 'IP',
          is_measure: false,
          pinyin: 'IP',
          event_id: 95,
          name: '$ip',
          data_type: 'string',
          event_name: '$AppClick',
          id: 279,
          has_db_column_name: true,
          not_select_group: false,
        },
        {
          db_column_name: 'p__lib',
          is_dimension: true,
          is_permitted: true,
          has_dict: false,
          is_common: false,
          cname: 'SDK 类型',
          is_measure: false,
          pinyin: 'SDK  lei xing',
          event_id: 95,
          name: '$lib',
          data_type: 'string',
          event_name: '$AppClick',
          id: 267,
          has_db_column_name: true,
          not_select_group: false,
        },
        {
          db_column_name: 'p__element_id',
          is_dimension: true,
          is_permitted: true,
          has_dict: false,
          is_common: false,
          cname: '元素 ID',
          is_measure: false,
          pinyin: 'yuan su  ID',
          event_id: 95,
          name: '$element_id',
          data_type: 'string',
          event_name: '$AppClick',
          id: 485,
          has_db_column_name: true,
          not_select_group: false,
        },
        {
          db_column_name: 'p__element_position',
          is_dimension: true,
          is_permitted: true,
          has_dict: false,
          is_common: false,
          cname: '元素位置',
          is_measure: false,
          pinyin: 'yuan su wei zhi',
          event_id: 95,
          name: '$element_position',
          data_type: 'string',
          event_name: '$AppClick',
          id: 535,
          has_db_column_name: true,
          not_select_group: false,
        },
        {
          db_column_name: 'p__element_content',
          is_dimension: true,
          is_permitted: true,
          has_dict: false,
          is_common: false,
          cname: '元素内容',
          is_measure: false,
          pinyin: 'yuan su nei rong',
          event_id: 95,
          name: '$element_content',
          data_type: 'string',
          event_name: '$AppClick',
          id: 486,
          has_db_column_name: true,
          not_select_group: false,
        },
        {
          db_column_name: 'p__element_type',
          is_dimension: true,
          is_permitted: true,
          has_dict: false,
          is_common: false,
          cname: '元素类型',
          is_measure: false,
          pinyin: 'yuan su lei xing',
          event_id: 95,
          name: '$element_type',
          data_type: 'string',
          event_name: '$AppClick',
          id: 488,
          has_db_column_name: true,
          not_select_group: false,
        },
        {
          db_column_name: 'p__element_path',
          is_dimension: true,
          is_permitted: true,
          has_dict: false,
          is_common: false,
          cname: '元素路径',
          is_measure: false,
          pinyin: 'yuan su lu jing',
          event_id: 95,
          name: '$element_path',
          data_type: 'string',
          event_name: '$AppClick',
          id: 534,
          has_db_column_name: true,
          not_select_group: false,
        },
        {
          db_column_name: 'p__element_selector',
          is_dimension: true,
          is_permitted: true,
          has_dict: false,
          is_common: false,
          cname: '元素选择器',
          is_measure: false,
          pinyin: 'yuan su xuan ze qi',
          event_id: 95,
          name: '$element_selector',
          data_type: 'string',
          event_name: '$AppClick',
          id: 533,
          has_db_column_name: true,
          not_select_group: false,
        },
        {
          db_column_name: 'p__track_signup_original_id',
          is_dimension: true,
          is_permitted: true,
          has_dict: false,
          is_common: false,
          cname: '关联原始 ID',
          is_measure: false,
          pinyin: 'guan lian yuan shi  ID',
          event_id: 95,
          name: '$track_signup_original_id',
          data_type: 'string',
          event_name: '$AppClick',
          id: 336,
          has_db_column_name: true,
          not_select_group: false,
        },
        {
          db_column_name: 'p__country',
          is_dimension: true,
          is_permitted: true,
          has_dict: false,
          is_common: false,
          cname: '国家',
          is_measure: false,
          pinyin: 'guo jia',
          event_id: 95,
          name: '$country',
          data_type: 'string',
          event_name: '$AppClick',
          id: 530,
          has_db_column_name: true,
          not_select_group: false,
        },
        {
          db_column_name: 'p__screen_width',
          is_dimension: true,
          is_permitted: true,
          has_dict: false,
          is_common: false,
          cname: '屏幕宽度',
          unit: '像素',
          is_measure: true,
          pinyin: 'ping mu kuan du',
          event_id: 95,
          name: '$screen_width',
          data_type: 'number',
          event_name: '$AppClick',
          id: 516,
          has_db_column_name: true,
          not_select_group: false,
        },
      ]);
    }, 200);
  });

export const getProProps = () =>
  new Promise((resolve) => {
    setTimeout(() => {
      resolve([
        {
          name: 'title',
          cname: 'title',
          data_type: 'string',
        },
        {
          name: 'channel',
          cname: 'channel',
          data_type: 'string',
        },
        {
          name: 'category',
          cname: 'category',
          data_type: 'list',
        },
        {
          name: 'tags',
          cname: 'tags',
          data_type: 'string',
        },
        {
          name: 'publish_time',
          cname: 'publish_time',
          data_type: 'datetime',
        },
        {
          name: 'content',
          cname: 'content',
          data_type: 'string',
        },
        {
          name: 'item_type',
          cname: '物品类型',
          data_type: 'string',
        },
        {
          name: 'item_id',
          cname: '物品ID',
          data_type: 'string',
        },
      ]);
    }, 200);
  });
export const getWhiteProps = () =>
  new Promise((resolve) => {
    setTimeout(() => {
      resolve([
        {
          name: 'title',
          cname: 'title',
          data_type: 'string',
        },
        {
          name: 'channel',
          cname: 'channel',
          data_type: 'string',
        },
        {
          name: 'category',
          cname: 'category',
          data_type: 'list',
        },
        {
          name: 'tags',
          cname: 'tags',
          data_type: 'string',
        },
        {
          name: 'publish_time',
          cname: 'publish_time',
          data_type: 'datetime',
        },
        {
          name: 'content',
          cname: 'content',
          data_type: 'string',
        },
        {
          name: 'item_type',
          cname: '物品类型',
          data_type: 'string',
        },
        {
          name: 'item_id',
          cname: '物品ID',
          data_type: 'string',
        },
      ]);
    }, 200);
  });
